os: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'

cache:
  - node_modules

branches:
  only:
    - master

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install --force

build_script:
  - yarn check-prettier
  - yarn build

test_script:
  - ./script/test-appveyor.bat
