os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "8.9.0"

cache:
  - node_modules

branches:
  only:
    - master

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g yarn@1.3.2
  - yarn install --force

# TODO: move this to test_script after we have actual code to work with
build_script:
  - ./script/test-appveyor.bat
